export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAIL = "CHANGE_PASS_FAIL";


export const FIND_ALL = "FIND_ALL";
export const BAN_USER_SUCCESS = "BAN_USER_SUCCESS";
export const BAN_USER_FAIL = "BAN_USER_FAIL";
export const ADD_USER_ROLE_SUCCESS = "ADD_USER_ROLE_SUCCESS";
export const ADD_USER_ROLE_FAIL = "ADD_USER_ROLE_FAIL";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAIL = "APPROVE_USER_FAIL";


export const CREATE_SELECTION_ORDER_SUCCESS = "CREATE_SELECTION_ORDER_SUCCESS";
export const CREATE_INSPECTION_ORDER_SUCCESS = "CREATE_INSPECTION_ORDER_SUCCESS";
export const UPDATE_INSPECTION_ORDER_SUCCESS = "UPDATE_INSPECTION_ORDER_SUCCESS";
export const UPDATE_SELECTION_ORDER_SUCCESS = "UPDATE_SELECTION_ORDER_SUCCESS";
export const CHANGE_ORDER_STATUS_SUCCESS = "CHANGE_ORDER_STATUS_SUCCESS";
export const CREATE_SELECTION_ORDER_FAIL = "CREATE_SELECTION_ORDER_FAIL";
export const CREATE_INSPECTION_ORDER_FAIL = "CREATE_INSPECTION_ORDER_FAIL";
export const UPDATE_INSPECTION_ORDER_FAIL = "UPDATE_INSPECTION_ORDER_FAIL";
export const UPDATE_SELECTION_ORDER_FAIL = "UPDATE_SELECTION_ORDER_FAIL";
export const CHANGE_ORDER_STATUS_FAIL = "CHANGE_ORDER_STATUS_FAIL";
export const GET_USERS_ORDERS = "GET_USERS_ORDERS";