export const GET_AUTOPICKER_ORDERS = "GET_AUTOPICKER_ORDERS";
export const GET_INSPECTION_ORDER = "GET_INSPECTION_ORDER";
export const GET_INSPECTION_REPORT = "GET_INSPECTION_REPORT";
export const SAVE_NEW_SELECTION_REPORT_FAIL = "SAVE_NEW_SELECTION_REPORT_FAIL";
export const SAVE_NEW_SELECTION_REPORT_SUCCESS = "SAVE_NEW_SELECTION_REPORT_SUCCESS";
export const SAVE_EDITED_SELECTION_REPORT_SUCCESS = "SAVE_EDITED_SELECTION_REPORT_SUCCESS";
export const SAVE_EDITED_SELECTION_REPORT_FAIL = "SAVE_EDITED_SELECTION_REPORT_FAIL";

export const GET_SELECTION_REPORT = "GET_SELECTION_REPORT";
export const CREATE_SELECTION_REPORT = "CREATE_SELECTION_REPORT";
export const EDIT_SELECTION_REPORT = "EDIT_SELECTION_REPORT";

export const CLEAN_REPORT = "CLEAN_REPORT";

export const CREATE_INSPECTION_REPORT = "CREATE_INSPECTION_REPORT";
export const EDIT_INSPECTION_MAIN_INFO = "EDIT_INSPECTION_MAIN_INFO";
export const EDIT_INSPECTION_SALON_REPORT = "EDIT_INSPECTION_SALON_REPORT";
export const EDIT_INSPECTION_BODY_REPORT = "EDIT_INSPECTION_BODY_REPORT";
export const EDIT_INSPECTION_ELECTRIC_REPORT = "EDIT_INSPECTION_ELECTRIC_REPORT";
export const EDIT_INSPECTION_PENDANT_REPORT = "EDIT_INSPECTION_PENDANT_REPORT";
export const EDIT_INSPECTION_ENGINE_REPORT = "EDIT_INSPECTION_ENGINE_REPORT";
export const EDIT_INSPECTION_TRANSMISSION_REPORT = "EDIT_INSPECTION_TRANSMISSION_REPORT";

export const SAVE_EDITTED_INSPECTION_MAIN_INFO = "EDIT_INSPECTION_MAIN_INFO";
export const SAVE_EDITTED_INSPECTION_SALON_REPORT = "EDIT_INSPECTION_SALON_REPORT";
export const SAVE_EDITTED_INSPECTION_BODY_REPORT = "EDIT_INSPECTION_BODY_REPORT";
export const SAVE_EDITTED_ELECTRIC_REPORT = "EDIT_INSPECTION_ELECTRIC_REPORT";
export const SAVE_EDITTED_PENDANT_REPORT = "EDIT_INSPECTION_PENDANT_REPORT";
export const SAVE_EDITTED_ENGINE_REPORT = "EDIT_INSPECTION_ENGINE_REPORT";
export const SAVE_EDITTED_TRANSMISSION_REPORT = "EDIT_INSPECTION_TRANSMISSION_REPORT";


export const EDIT_BODY_PART_DESCRIPTION = "EDIT_BODY_PART_DESCRIPTION";