export const GET_AUTOPICKER_ORDERS = "GET_AUTOPICKER_ORDERS";

export const SAVE_NEW_SELECTION_REPORT_FAIL = "SAVE_NEW_SELECTION_REPORT_FAIL";
export const SAVE_NEW_SELECTION_REPORT_SUCCESS = "SAVE_NEW_SELECTION_REPORT_SUCCESS";
export const SAVE_EDITED_SELECTION_REPORT_SUCCESS = "SAVE_EDITED_SELECTION_REPORT_SUCCESS";
export const SAVE_EDITED_SELECTION_REPORT_FAIL = "SAVE_EDITED_SELECTION_REPORT_FAIL";

export const GET_SELECTION_REPORT = "GET_SELECTION_REPORT";
export const CREATE_SELECTION_REPORT = "CREATE_SELECTION_REPORT";
export const EDIT_SELECTION_REPORT = "EDIT_SELECTION_REPORT";